apiVersion: apps/v1
kind: Deployment
metadata:
  name: hawtio-online-console-plugin
  labels:
    app: hawtio-online-console-plugin
    app.kubernetes.io/component: hawtio-online-console-plugin
    app.kubernetes.io/instance: hawtio-online-console-plugin
    app.kubernetes.io/part-of: hawtio-online-console-plugin
    app.openshift.io/runtime-namespace: hawtio-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hawtio-online-console-plugin
  template:
    metadata:
      labels:
        app: hawtio-online-console-plugin
    spec:
      containers:
        - name: hawtio-online-console-plugin
          image: quay.io/hawtio/hawtio-online-console-plugin:0.0.1
          ports:
            - containerPort: 9443
              protocol: TCP
          args: [ "-g", "daemon off;"]
          command:
          - nginx
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
          volumeMounts:
            - name: plugin-serving-cert
              readOnly: true
              mountPath: /var/serving-cert
            - name: nginx-conf
              readOnly: true
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: plugin-serving-cert
          secret:
            secretName: plugin-serving-cert
            defaultMode: 420
        - name: nginx-conf
          configMap:
            name: nginx-conf
            defaultMode: 420
      restartPolicy: Always
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
