apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  name: hawtio-online-console-plugin
spec:
  displayName: 'OpenShift Console Hawtio Online Plugin'
  backend:
    type: Service
    service:
      name: hawtio-online-console-plugin
      namespace: hawtio-dev
      port: 9443
      basePath: '/'
  proxy:
    - type: Service
      alias: gateway
      authorization: UserToken
      endpoint:
        type: Service
        service:
          name: hawtio-online-console-plugin-gateway
          namespace: hawtio-dev
          port: 8443
    - type: Service
      alias: echo
      authorization: UserToken
      endpoint:
        type: Service
        service:
          name: http-echo
          namespace: hawtio-dev
          port: 8443
