apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  name: hawtio-online-console-plugin
spec:
  displayName: 'OpenShift Console Hawtio Online Plugin'
  backend:
    type: Service
    service:
      name: hawtio-online-console-plugin
      namespace: hawtio-dev
      port: 9443
      basePath: '/'
