apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: hawtio-online-console-plugin-gateway-serving
  name: hawtio-online-console-plugin-gateway
  labels:
    app: hawtio-online-console-plugin-gateway
    app.kubernetes.io/component: hawtio-online-console-plugin-gateway
    app.kubernetes.io/instance: hawtio-online-console-plugin-gateway
    app.kubernetes.io/part-of: hawtio-online-console-plugin
spec:
  ports:
    - name: 8443-tcp
      protocol: TCP
      port: 8443
      targetPort: express
  selector:
    app: hawtio-online-console-plugin-gateway
  type: ClusterIP
  sessionAffinity: None
