apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Values.gateway.secrets.proxy.name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "hawtio-online-console-plugin.app.labels" .Values.gateway | indent 4 }}
data:
{{ include "hawtio-online-console-plugin.proxy.gen-cert" . }}
