/**
 * Hawtio-Online plugin name
 * Hawtio-Online version number
 * Injected by build system
 */
declare const HAWTIO_ONLINE_PACKAGE_PLUGIN_NAME: string
declare const HAWTIO_ONLINE_PACKAGE_VERSION: string
declare const HAWTIO_ONLINE_PUBLIC_PATH: string

const HAWTIO_ONLINE_PLUGIN_NAME = HAWTIO_ONLINE_PACKAGE_PLUGIN_NAME

const HAWTIO_ONLINE_VERSION = HAWTIO_ONLINE_PACKAGE_VERSION

const HAWTIO_ONLINE_PLUGIN_PUBLIC_PATH = HAWTIO_ONLINE_PUBLIC_PATH

const PLUGIN_BASE_PATH = `/api/plugins/${HAWTIO_ONLINE_PLUGIN_NAME}${HAWTIO_ONLINE_PLUGIN_PUBLIC_PATH}`

export { HAWTIO_ONLINE_PLUGIN_NAME, HAWTIO_ONLINE_VERSION, PLUGIN_BASE_PATH }
